# Generated by Django 3.1.1 on 2020-09-07 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0003_auto_20200907_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='akun_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='direkturrs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='akun_direktur', to=settings.AUTH_USER_MODEL),
        ),
    ]
