# Generated by Django 3.1.1 on 2020-09-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0005_auto_20200907_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
