# Generated by Django 3.1.1 on 2020-09-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0006_auto_20200907_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
