# Generated by Django 3.1.1 on 2020-09-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daerah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daerah', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasilitas', models.CharField(max_length=50, unique=True)),
                ('keterangan', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poliklinik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliklinik', models.CharField(max_length=50, unique=True)),
                ('keterangan', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RumahSakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('alamat', models.TextField(max_length=100)),
                ('no_telp', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('daerah', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='Daerah', to='rumahsakit.daerah')),
                ('fasilitas', models.ManyToManyField(db_constraint=False, related_name='Fasilitas', to='rumahsakit.Fasilitas')),
                ('poliklinik', models.ManyToManyField(db_constraint=False, related_name='Poliklinik', to='rumahsakit.Poliklinik')),
            ],
        ),
    ]
