# Generated by Django 3.1.1 on 2020-09-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumahsakit', '0002_rumahsakit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumahsakit',
            name='deskripsi',
            field=models.TextField(),
        ),
    ]
