# Generated by Django 3.1.1 on 2020-09-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumahsakit', '0003_auto_20200907_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasilitas',
            name='keterangan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='poliklinik',
            name='keterangan',
            field=models.TextField(),
        ),
    ]
