# Generated by Django 3.1.1 on 2020-09-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumahsakit', '0004_auto_20200907_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fasilitas',
            name='keterangan',
        ),
    ]
