# Generated by Django 2.2.8 on 2021-01-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumahsakit', '0005_remove_fasilitas_keterangan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daerah',
            options={'ordering': ['daerah']},
        ),
        migrations.AlterModelOptions(
            name='fasilitas',
            options={'ordering': ['fasilitas']},
        ),
        migrations.AlterModelOptions(
            name='poliklinik',
            options={'ordering': ['poliklinik']},
        ),
        migrations.AlterModelOptions(
            name='rumahsakit',
            options={'ordering': ['nama']},
        ),
        migrations.AlterField(
            model_name='rumahsakit',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/RS/'),
        ),
    ]
