# Generated by Django 2.2.8 on 2021-03-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumahsakit', '0006_auto_20210110_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterRumahSakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('alamat', models.TextField(max_length=100)),
                ('no_telp', models.CharField(max_length=50)),
                ('file_akreditansi', models.FileField(upload_to='img/RS/Register/')),
            ],
        ),
    ]
