# Generated by Django 2.2.8 on 2021-03-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rumahsakit', '0007_registerrumahsakit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerrumahsakit',
            options={'ordering': ['nama']},
        ),
        migrations.AddField(
            model_name='registerrumahsakit',
            name='daerah',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='RDaerah', to='rumahsakit.Daerah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerrumahsakit',
            name='fasilitas',
            field=models.ManyToManyField(db_constraint=False, related_name='RFasilitas', to='rumahsakit.Fasilitas'),
        ),
        migrations.AddField(
            model_name='registerrumahsakit',
            name='poliklinik',
            field=models.ManyToManyField(db_constraint=False, related_name='RPoliklinik', to='rumahsakit.Poliklinik'),
        ),
    ]
