# Generated by Django 2.2.8 on 2021-03-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumahsakit', '0008_auto_20210302_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterHUMASRS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('email', models.TextField(max_length=100)),
                ('no_telp', models.CharField(max_length=50)),
                ('foto_diri', models.FileField(upload_to='img/RS/Register/humas/')),
                ('foto_ktp', models.FileField(upload_to='img/RS/Register/humas/')),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.RemoveField(
            model_name='registerrumahsakit',
            name='daerah',
        ),
        migrations.RemoveField(
            model_name='registerrumahsakit',
            name='fasilitas',
        ),
        migrations.RemoveField(
            model_name='registerrumahsakit',
            name='poliklinik',
        ),
        migrations.AlterField(
            model_name='registerrumahsakit',
            name='file_akreditansi',
            field=models.FileField(upload_to='img/RS/Register/rumahsakit/'),
        ),
    ]
