# Generated by Django 2.2.8 on 2021-03-07 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rumahsakit', '0011_auto_20210306_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerhumasrs',
            name='register_rumahsakit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='register_rs', to='rumahsakit.RegisterRumahSakit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerhumasrs',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registerhumasrs',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
