# Generated by Django 2.2.8 on 2021-03-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumahsakit', '0015_auto_20210307_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerhumasrs',
            name='foto_diri',
            field=models.FileField(upload_to='img/RS/Register/humas/foto_diri/'),
        ),
        migrations.AlterField(
            model_name='registerhumasrs',
            name='foto_ktp',
            field=models.FileField(upload_to='img/RS/Register/humas/foto_ktp/'),
        ),
    ]
