# Generated by Django 3.1.1 on 2020-09-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rumahsakit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesialis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spesialis', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100)),
                ('Jenkel', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tgl_lahir', models.DateField()),
                ('pengalaman', models.CharField(max_length=3)),
                ('pendidikan', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('rumahsakit', models.ManyToManyField(db_constraint=False, related_name='RumahSakit', to='rumahsakit.RumahSakit')),
                ('spesialis', models.ManyToManyField(db_constraint=False, related_name='Spesialis', to='dokter.Spesialis')),
            ],
        ),
    ]
