# Generated by Django 3.1.1 on 2020-09-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default=1, upload_to='img/dokter/'),
            preserve_default=False,
        ),
    ]
