# Generated by Django 3.1.1 on 2020-11-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokter', '0002_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='/static/img/doctor-icon.png', upload_to='img/dokter/'),
        ),
    ]
