# Generated by Django 3.1.1 on 2020-11-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumahsakit', '0005_remove_fasilitas_keterangan'),
        ('dokter', '0005_remove_doctor_rumahsakit'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rumahsakit',
            field=models.ManyToManyField(db_constraint=False, related_name='RumahSakit', to='rumahsakit.RumahSakit'),
        ),
    ]
