# Generated by Django 3.1.1 on 2020-11-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokter', '0007_auto_20201109_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='img/dokter/default.png', upload_to='img/dokter/'),
        ),
    ]
